export const PERMISSION_GROUPS = {
  ACCOUNTS: 'ACCOUNTS',
  USERS: 'USERS',
  DEPARTMENTS: 'DEPARTMENTS',
  PROFILES: 'PROFILES',
  PERMISSIONS: 'PERMISSIONS',
  COLLABORATORS: 'COLLABORATORS',
  CUSTOMERS: 'CUSTOMERS',
  PROJECTS: 'PROJECTS',
  TEAMS: 'TEAMS',
  ROLES: 'ROLES',
  COST_CENTERS: 'COST_CENTERS',
  SERVICES: 'SERVICES',
  SERVICE_CATEGORIES: 'SERVICE_CATEGORIES',
  SERVICE_FRONTS: 'SERVICE_FRONTS',
  SERVICE_ORDERS: 'SERVICE_ORDERS',
  SERVICE_ORDER_ITEMS: 'SERVICE_ORDER_ITEMS',
  UNITS: 'UNITS',
  PROJECT_STATUSES: 'PROJECT_STATUSES',
  PROJECT_ATTACHMENTS: 'PROJECT_ATTACHMENTS',
  PROJECT_CONTRACT_ATTACHMENTS: 'PROJECT_CONTRACT_ATTACHMENTS',
  PROJECT_OCCURRENCES: 'PROJECT_OCCURRENCES',
  PROJECT_TEAMS: 'PROJECT_TEAMS',
  PROJECT_SERVICE_FRONTS: 'PROJECT_SERVICE_FRONTS',
  PROJECT_CRONOGRAMS: 'PROJECT_CRONOGRAMS',
  PROJECT_CRONOGRAM_ITEMS: 'PROJECT_CRONOGRAM_ITEMS',
  PROJECT_CRONOGRAM_ITEM_MEASUREMENTS: 'PROJECT_CRONOGRAM_ITEM_MEASUREMENTS',
  OCCURRENCE_CATEGORIES: 'OCCURRENCE_CATEGORIES',
  COLLABORATOR_CHECKINS: 'COLLABORATOR_CHECKINS',
  COLLABORATOR_ATTACHMENTS: 'COLLABORATOR_ATTACHMENTS',
  COLLABORATOR_IMAGES: 'COLLABORATOR_IMAGES',
  PROFILE_PERMISSIONS: 'PROFILE_PERMISSIONS',
  TEAM_MEMBERS: 'TEAM_MEMBERS',
  CHECKIN_VALIDATIONS: 'CHECKIN_VALIDATIONS',
  SUPPLIERS: 'SUPPLIERS',
  MATERIAL_CATEGORIES: 'MATERIAL_CATEGORIES',
  MATERIAL_TYPES: 'MATERIAL_TYPES',
  MATERIALS: 'MATERIALS',
  STOCKS: 'STOCKS',
  STOCK_RECORDS: 'STOCK_RECORDS',
} as const;

export const PERMISSION_ACTIONS = {
  LIST: 'LIST',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;

// Helper para gerar chaves de permissão
export function buildPermissionKey(group: string, action: string): string {
  return `${group}_${action}`;
}

// Lista de todas as chaves de grupos para validação
export type PermissionGroupKey = keyof typeof PERMISSION_GROUPS;
export type PermissionActionKey = keyof typeof PERMISSION_ACTIONS;
